//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;

namespace Empresa.MoneyManagerModel
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
	[VSShell::ProvideToolWindow(typeof(MoneyManagerModelExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(MoneyManagerModelExplorerToolWindow), Constants.MoneyManagerModelEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@MoneyManagerModelToolboxTab;Empresa.MoneyManagerModel.Dsl.dll", "Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@UserSpecToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.UserSpecToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"UserSpec", 
					"@UserSpecToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@AccountSpecToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.AccountSpecToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AccountSpec", 
					"@AccountSpecToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@TransactionSpecToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.TransactionSpecToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransactionSpec", 
					"@TransactionSpecToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@AttributeTypeToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.AttributeTypeToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AttributeType", 
					"@AttributeTypeToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@AssociationToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.AssociationToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Association", 
					"@AssociationToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@UserAttributeToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.UserAttributeToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"UserAttribute", 
					"@UserAttributeToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@AccountAttributeToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.AccountAttributeToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AccountAttribute", 
					"@AccountAttributeToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@TransactionAttributeToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.TransactionAttributeToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransactionAttribute", 
					"@TransactionAttributeToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@AccAttAttTypeToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.AccAttAttTypeToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AccAttAttType", 
					"@AccAttAttTypeToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@AccSpAssToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.AccSpAssToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AccSpAss", 
					"@AccSpAssToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@AssAccSpToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.AssAccSpToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AssAccSp", 
					"@AssAccSpToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@AssTranSpToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.AssTranSpToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AssTranSp", 
					"@AssTranSpToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@AssUserSpToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.AssUserSpToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AssUserSp", 
					"@AssUserSpToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 12)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@TransAttAttTypeToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.TransAttAttTypeToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransAttAttType", 
					"@TransAttAttTypeToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 13)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@TransSpAssToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.TransSpAssToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"TransSpAss", 
					"@TransSpAssToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 14)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@UserAttAttTypeToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.UserAttAttTypeToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"UserAttAttType", 
					"@UserAttAttTypeToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 15)]
	[VSShell::ProvideStaticToolboxItem("Empresa.MoneyManagerModel.MoneyManagerModelToolboxTab",
					"@UserSpAssToolboxItem;Empresa.MoneyManagerModel.Dsl.dll", 
					"Empresa.MoneyManagerModel.UserSpAssToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"UserSpAss", 
					"@UserSpAssToolboxBitmap;Empresa.MoneyManagerModel.Dsl.dll", 
					0xff00ff,
					Index = 16)]
	[VSShell::ProvideEditorFactory(typeof(MoneyManagerModelEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(MoneyManagerModelEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(MoneyManagerModelEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"MoneyManagerModel", typeof(MoneyManagerModelEditorFactory))]

	internal abstract partial class MoneyManagerModelPackageBase : DslShell::AsyncModelingPackage
	{
		protected global::Empresa.MoneyManagerModel.MoneyManagerModelToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected async override Task InitializeAsync(CancellationToken cancellationToken, IProgress<VSShell.ServiceProgressData> progress)
		{
			await base.InitializeAsync(cancellationToken, progress);

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new MoneyManagerModelEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::Empresa.MoneyManagerModel.MoneyManagerModelToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			MoneyManagerModelCommandSet commandSet = new MoneyManagerModelCommandSet(this);
			await commandSet.InitializeAsync(cancellationToken);
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			MoneyManagerModelClipboardCommandSet clipboardCommandSet = new MoneyManagerModelClipboardCommandSet(this);
			await clipboardCommandSet.InitializeAsync(cancellationToken);
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(MoneyManagerModelExplorerToolWindow));

			if (cancellationToken.IsCancellationRequested)
			{
				return;
			}

			await JoinableTaskFactory.SwitchToMainThreadAsync();

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			await this.SetupDynamicToolboxAsync(cancellationToken);
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch (global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}

		public override VSShellInterop::IVsAsyncToolWindowFactory GetAsyncToolWindowFactory(Guid toolWindowType)
		{
			if (toolWindowType == typeof(MoneyManagerModelExplorerToolWindow).GUID)
			{
				return this;
			}

			return base.GetAsyncToolWindowFactory(toolWindowType);
		}
	}
}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace Empresa.MoneyManagerModel
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::Empresa.MoneyManagerModel.MoneyManagerModelDirectiveProcessor), global::Empresa.MoneyManagerModel.MoneyManagerModelDirectiveProcessor.MoneyManagerModelDirectiveProcessorName, "A directive processor that provides access to MoneyManagerModel files")]
	[global::System.Runtime.InteropServices.Guid(Constants.MoneyManagerModelPackageId)]
	internal sealed partial class MoneyManagerModelPackage : MoneyManagerModelPackageBase
	{
	}
}