package MoneyManagerGeneratedCode.controller;

/*Generated by MPS */

import MoneyManagerGeneratedCode.model.User;
import java.util.Scanner;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.util.List;
import MoneyManagerGeneratedCode.model.AccountBase;
import java.util.ArrayList;

public class UserController {


  public UserController() {
  }

  public User addUser() {
    Scanner sc = new Scanner(System.in);
    System.out.println("User Name: ");
    String name = sc.nextLine();
    System.out.println("User Birthday: ");
    String date = sc.nextLine();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
    LocalDate localDate = LocalDate.parse(date, formatter);
    List<AccountBase> accountBaseList = new ArrayList<>();
    return new User(name, accountBaseList, localDate);
  }
}
