package MoneyManagerGeneratedCode.model.category;

/*Generated by MPS */


public class IncomeCategory extends Category {

  private final String description;

  public IncomeCategory(String name) {
    super(name);
    this.description = "Income";
  }
  @Override
  public String toString() {
    String nameString = "Name: " + this.getName() + "\n";
    String descriptionString = "Description: " + description + "\n";
    return "Income Category => \n" + nameString + descriptionString;
  }
}
