<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="edom204epsilon" nsURI="http://www.example.org/edom204epsilon"
    nsPrefix="edom204epsilon">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nameMustHaveName nameMustBegreaterThan1Char"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nameMustHaveName" value="self.name.oclIsUndefined()"/>
      <details key="nameMustBegreaterThan1Char" value="self.name.size() > 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userspec" upperBound="-1"
        eType="#//UserSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accountspec" upperBound="-1"
        eType="#//AccountSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactionspec" upperBound="-1"
        eType="#//TransactionSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="useraccountassociation"
        upperBound="-1" eType="#//UserAccountAssociation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounttransactionassociation"
        upperBound="-1" eType="#//AccountTransactionAssociation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userattribute" upperBound="-1"
        eType="#//UserAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="useraccountassociation"
        upperBound="-1" eType="#//UserAccountAssociation" eOpposite="#//UserAccountAssociation/userspec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccountSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accountattribute" upperBound="-1"
        eType="#//AccountAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="useraccountassociation"
        upperBound="-1" eType="#//UserAccountAssociation" eOpposite="#//UserAccountAssociation/accountspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounttransactionassociation"
        upperBound="-1" eType="#//AccountTransactionAssociation" eOpposite="#//AccountTransactionAssociation/accountspec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactionattribute" upperBound="-1"
        eType="#//TransactionAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounttransactionassociation"
        upperBound="-1" eType="#//AccountTransactionAssociation" eOpposite="#//AccountTransactionAssociation/transactionspec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserAttribute">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nameMustHaveName nameMustBegreaterThan1Char"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nameMustHaveName" value="self.name.oclIsUndefined()"/>
      <details key="nameMustBegreaterThan1Char" value="self.name.size() > 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//AttributeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccountAttribute">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nameMustHaveName nameMustBegreaterThan1Char"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nameMustHaveName" value="self.name.oclIsUndefined()"/>
      <details key="nameMustBegreaterThan1Char" value="self.name.size() > 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//AttributeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionAttribute">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nameMustHaveName nameMustBegreaterThan1Char"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nameMustHaveName" value="self.name.oclIsUndefined()"/>
      <details key="nameMustBegreaterThan1Char" value="self.name.size() > 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//AttributeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttributeType"/>
  <eClassifiers xsi:type="ecore:EClass" name="UserAccountAssociation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userspec" lowerBound="1"
        eType="#//UserSpec" eOpposite="#//UserSpec/useraccountassociation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accountspec" lowerBound="1"
        eType="#//AccountSpec" eOpposite="#//AccountSpec/useraccountassociation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccountTransactionAssociation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accountspec" lowerBound="1"
        eType="#//AccountSpec" eOpposite="#//AccountSpec/accounttransactionassociation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactionspec" lowerBound="1"
        eType="#//TransactionSpec" eOpposite="#//TransactionSpec/accounttransactionassociation"/>
  </eClassifiers>
</ecore:EPackage>
