//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa.MoneyManagerModel
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "MoneyManagerModel";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"MoneyManagerModel";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Empresa";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID MoneyManagerModelDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MoneyManagerModelCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID MoneyManagerModelExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MoneyManagerModelCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewMoneyManagerModelExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MoneyManagerModelCommandSetId), 0x0001);
	
		// Package identifier
		public const string MoneyManagerModelPackageId = "06612bd9-348e-48fc-9d2f-1c2e08c52e66";
		
		// Editor factory identifier
		public const string MoneyManagerModelEditorFactoryId = "fa31fe3c-b99e-46d3-83fe-47ad712d35ce";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string MoneyManagerModelModelExplorerToolWindowId = "bd4b66de-004d-48b1-8357-b43e651a9d71";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Empresa.MoneyManagerModel
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string MoneyManagerModelCommandSetId = "a1046041-02fe-4167-893f-cdb32fdd5107";
	}
}