package moneyManager.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AccountAttribute = 0;
  public static final int AccountGroupSpec = 1;
  public static final int AccountSpec = 2;
  public static final int AccountSpecReference = 3;
  public static final int AccountTransactionAssociation = 4;
  public static final int AccountTransactionAssociationReference = 5;
  public static final int CategoryAttribute = 6;
  public static final int CategorySpec = 7;
  public static final int Model = 8;
  public static final int TransactionAttribute = 9;
  public static final int TransactionCategoryAssociation = 10;
  public static final int TransactionCategoryAssociationReference = 11;
  public static final int TransactionSpec = 12;
  public static final int UserAccountAssociation = 13;
  public static final int UserAccountAssociationReference = 14;
  public static final int UserAttribute = 15;
  public static final int UserSpec = 16;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x9a5f9a2ebfeb4763L, 0xbcb7ba78024d6876L);
    builder.put(0x781619bd78713127L, AccountAttribute);
    builder.put(0x53f441f22bf9e915L, AccountGroupSpec);
    builder.put(0x781619bd78713105L, AccountSpec);
    builder.put(0x53f441f22bf9e95fL, AccountSpecReference);
    builder.put(0x53f441f22bf9e949L, AccountTransactionAssociation);
    builder.put(0x53f441f22bf9e94cL, AccountTransactionAssociationReference);
    builder.put(0x53f441f22c20b44cL, CategoryAttribute);
    builder.put(0x53f441f22c20b449L, CategorySpec);
    builder.put(0x781619bd78713101L, Model);
    builder.put(0x781619bd7871312cL, TransactionAttribute);
    builder.put(0x53f441f22c220907L, TransactionCategoryAssociation);
    builder.put(0x53f441f22c22090fL, TransactionCategoryAssociationReference);
    builder.put(0x781619bd78713123L, TransactionSpec);
    builder.put(0x53f441f22bf9e91dL, UserAccountAssociation);
    builder.put(0x53f441f22bf9e93aL, UserAccountAssociationReference);
    builder.put(0x781619bd78713125L, UserAttribute);
    builder.put(0x781619bd78713102L, UserSpec);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
