package moneyManager.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class CapitalizeAccountSpecName_QuickFix extends QuickFix_Runtime {
  public CapitalizeAccountSpecName_QuickFix() {
    super(new SNodePointer("r:2a14342b-a65f-4017-82a3-0a33a55ab1c8(moneyManager.typesystem)", "8653132035600184764"));
  }
  public String getDescription(SNode node) {
    return "Capitalize the first letter";
  }
  public void execute(SNode node) {
    SPropertyOperations.set(((SNode) CapitalizeAccountSpecName_QuickFix.this.getField("account")[0]), PROPS.name$MnvL, SPropertyOperations.getString(((SNode) CapitalizeAccountSpecName_QuickFix.this.getField("account")[0]), PROPS.name$MnvL).substring(0, 1).toUpperCase() + SPropertyOperations.getString(((SNode) CapitalizeAccountSpecName_QuickFix.this.getField("account")[0]), PROPS.name$MnvL).substring(1));
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
