package moneyManager.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class DeleteUniqueUserSpec_QuickFix extends QuickFix_Runtime {
  public DeleteUniqueUserSpec_QuickFix() {
    super(new SNodePointer("r:2a14342b-a65f-4017-82a3-0a33a55ab1c8(moneyManager.typesystem)", "8653132035600299940"));
  }
  public String getDescription(SNode node) {
    return "Delete this User";
  }
  public void execute(SNode node) {
    SNodeOperations.deleteNode(((SNode) DeleteUniqueUserSpec_QuickFix.this.getField("user")[0]));
  }
}
