package SolutionMoneyManager.a_model;

/*Generated by MPS */

import java.io.Serializable;

public abstract class Category implements Serializable {
  private String name;

  private Category(String name) {
    this.name = name;
  }


  public String getName() {
    return this.name;
  }
  public void setName(String name) {
    this.name = name;
  }

  private String nameString = "Name: " + name + "\n";


  @Override
  public String toString() {
    return "Category => \n" + nameString;
  }
}
